import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderCard from "./components/header";
import FooterCard from "./components/footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <div>
          <HeaderCard/>
          <section style={{display:"flex",flexDirection:"row", marginTop:"40px"}}>
            <div style={{width:"180px"}}>

            </div>
            <div>
              {children}
            </div>
            <div style={{width:"180px"}}>

            </div>
          </section>
          <FooterCard/>

        </div>
      </body>
    </html>
  );
}
