export async function GET(request: Request, { params }: { params: { state: string; city: string } }) {
     let states=[
        {link:"alabama",display:"Alabama",description:"Alabama is a state in the United States"},
  {link:"alaska",display:"Alaska",description:"Alaska is a state in the United States"},
  {link:"arizona",display:"Arizona",description:"Arizona is a state in the United States"},
  {link:"arkansas",display:"Arkansas",description:"Arkansas is a state in the United States"},
  {link:"california",display:"California",description:"California is a state in the United States"},
  {link:"colorado",display:"Colorado",description:"Colorado is a state in the United States"},
  {link:"connecticut",display:"Connecticut",description:"Connecticut is a state in the United States"},
  {link:"delaware",display:"Delaware",description:"Delaware is a state in the United States"},
  {link:"florida",display:"Florida",description:"Florida is a state in the United States"},
  {link:"georgia",display:"Georgia",description:"Georgia is a state in the United States"},
  {link:"hawaii",display:"Hawaii",description:"Hawaii is a state in the United States"},
  {link:"idaho",display:"Idaho",description:"Idaho is a state in the United States"},
  {link:"illinois",display:"Illinois",description:"Illinois is a state in the United States"},
  {link:"indiana",display:"Indiana",description:"Indiana is a state in the United States"},
  {link:"iowa",display:"Iowa",description:"Iowa is a state in the United States"},
  {link:"kansas",display:"Kansas",description:"Kansas is a state in the United States"},
  {link:"kentucky",display:"Kentucky",description:"Kentucky is a state in the United States"},
  {link:"louisiana",display:"Louisiana",description:"Louisiana is a state in the United States"},
  {link:"maine",display:"Maine",description:"Maine is a state in the United States"},
{link:"maryland",display:"Maryland",description:"Maryland is a state in the United States"},
  {link:"massachusetts",display:"Massachusetts",description:"Massachusetts is a state in the United States"},
  {link:"michigan",display:"Michigan",description:"Michigan is a state in the United States"},
  {link:"minnesota",display:"Minnesota",description:"Minnesota is a state in the United States"},
  {link:"mississippi",display:"Mississippi",description:"Mississippi is a state in the United States"},
  {link:"missouri",display:"Missouri",description:"Missouri is a state in the United States"},
  {link:"montana",display:"Montana",description:"Montana is a state in the United States"},
  {link:"nebraska",display:"Nebraska",description:"Nebraska is a state in the United States"},
  {link:"nevada",display:"Nevada",description:"Nevada is a state in the United States"},
  {link:"new_hampshire",display:"New Hampshire",description:"New Hampshire is a state in the United States"},
  {link:"new_jersey",display:"New Jersey",description:"New Jersey is a state in the United States"},
  {link:"new_mexico",display:"New Mexico",description:"New Mexico is a state in the United States"},
  {link:"new_york",display:"New York",description:"New York is a state in the United States"},
  {link:"north_carolina",display:"North Carolina",description:"North Carolina is a state in the United States"},
  {link:"north_dakota",display:"North Dakota",description:"North Dakota is a state in the United States"},
  {link:"ohio",display:"Ohio",description:"Ohio is a state in the United States"},
  {link:"oklahoma",display:"Oklahoma",description:"Oklahoma is a state in the United States"},
  {link:"oregon",display:"Oregon",description:"Oregon is a state in the United States"},
  {link:"pennsylvania",display:"Pennsylvania",description:"Pennsylvania is a state in the United States"},
  {link:"rhode_island",display:"Rhode Island",description:"Rhode Island is a state in the United States"},
  {link:"south_carolina",display:"South Carolina",description:"South Carolina is a state in the United States"},
  {link:"south_dakota",display:"South Dakota",description:"South Dakota is a state in the United States"},
  {link:"tennessee",display:"Tennessee",description:"Tennessee is a state in the United States"},
  {link:"texas",display:"Texas",description:"Texas is a state in the United States"},
  {link:"utah",display:"Utah",description:"Utah is a state in the United States"},
  {link:"vermont",display:"Vermont",description:"Vermont is a state in the United States"},
 {link:"virginia",display:"Virginia",description:"Virginia is a state in the United States"},
  {link:"washington",display:"Washington",description:"Washington is a state in the United States"},
  {link:"west_virginia",display:"West Virginia",description:"West Virginia is a state in the United States"},
  {link:"wisconsin",display:"Wisconsin",description:"Wisconsin is a state in the United States"},
  {link:"wyoming",display:"Wyoming",description:"Wyoming is a state in the United States"}

     ]
     return new Response(JSON.stringify(states),{
    status: 200,
    headers: {'content-type': 'application/json'}
})
    
}